export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_TRANSACTIONS_FOR_DATE = "GET_TRANSACTIONS_FOR_DATE";

export const ADD_TRANSACTIION = "ADD_TRANSACTION";

export const UPDATE_TRANSACTION = "UPDATE_TRANSACTION";

export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
